### PR TITLE
removed background image

### PR DESCRIPTION
**Pull request by Sa-naiH**

### CODE REVIEW

**Comment by IriqM** [comment]
https://www.google.com/imgres?imgurl=http%3A%2F%2Fimg.huffingtonpost.com%2Fasset%2Fscalefit_630_noupscale%2F581392eb150000b900530700.jpg&imgrefurl=http%3A%2F%2Fwww.africanamerica.org%2Ftopic%2Fhow-black-people-built-social-media&docid=BTh7bW1jCkgYfM&tbnid=_pBw2dg4ZF4zLM%3A&vet=10ahUKEwiEobaV-YPVAhXFeD4KHdyRBR8QMwhBKBUwFQ..i&w=630&h=344&bih=967&biw=1920&q=black%20people%20technology&ved=0ahUKEwiEobaV-YPVAhXFeD4KHdyRBR8QMwhBKBUwFQ&iact=mrc&uact=8

**Comment by HenryWill** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjL7Iz4-IPVAhWEdz4KHWWCAR4QjRwIBw&url=https%3A%2F%2Fwww.supermicro.com%2Fproducts%2Fmotherboard%2FX11%2FX11SBA-LN4F.cfm&psig=AFQjCNE1pPO_PWhS7pINcOLm-hvsFBrodw&ust=1499955779165291

**Comment by IriqM** [comment]
what do you think about the picture above by me

**Comment by JoshuaMarshall1** [comment]
screenshot 2017-07-12 at 10 23 05 am
screenshot 2017-07-12 at 10 21 41 am

**Comment by JoshuaMarshall1** [comment]
I say one of those

**Comment by JordanGastion1** [comment]
1[]
(https://us.123rf.com/450wm/rawpixel/rawpixel1512/rawpixel151206876/49264732-students-learning-education-social-media-technology.jpg?ver=6)

**Comment by HenryWill** [comment]
![]URL
https://www.google.com/imgres?imgurl=https%3A%2F%2Fc1.staticflickr.com%2F4%2F3814%2F9182088790_371df44277_b.jpg&imgrefurl=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Fjdhancock%2F9182088790&docid=ZA232rqi0Wm5HM&tbnid=y3Hqe5urJ16c_M%3A&vet=10ahUKEwiVndq0-YPVAhXMdT4KHSNRAB0QMwjLAig9MD0..i&w=1024&h=681&bih=750&biw=1536&q=computer%20chip&ved=0ahUKEwiVndq0-YPVAhXMdT4KHSNRAB0QMwjLAig9MD0&iact=mrc&uact=8

**Comment by ChelseaB1** [comment]
![]
(https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-407970.jpg)

**Comment by JordanGastion1** [comment]
image

**Comment by HenryWill** [comment]
image

**Comment by JoshuaMarshall1** [comment]
screenshot 2017-07-12 at 10 23 05 am
screenshot 2017-07-12 at 10 21 41 am

**Comment by jaydint1** [comment]
image

**Comment by SierraC** [comment]
image

**Comment by JustinBCB4** [comment]
image

**Comment by jaydint1** [comment]
image

**Comment by jaydint1** [comment]
image

**Comment by HenryWill** [comment]
image

**Comment by DaChristianW** [comment]
![]
(https://mail.google.com/mail/u/0/?ui=2&ik=70039c3de9&view=fimg&th=15d3733d79ebd9a1&attid=0.3&disp=inline&realattid=b43cf7dbbc0b5338_0.1.1&safe=1&attbid=ANGjdJ8rH0Iyj9R4nUa9aqaf3vHKxsz7cHXx-3l-zvmDFIo5A4Wi4_XUCGK7-IExGdh1MZQvtD1TQ2-gSNT8aPc9BL5r2z_x_evNIcxWr3sHEAEqyR8pAvcOCD0LipU&ats=1499869734352&rm=15d3733d79ebd9a1&zw&sz=w1920-h937)

**Comment by IriqM** [comment]
jordan is merging

**Comment by DaChristianW** [comment]
click the link

**Comment by DaChristianW** [comment]
dji_0023

**Pull request merged**
